import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Header from "@/components/header";
import Footer from "@/components/footer";
import Script from "next/script"; // Import Script component from Next.js

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "RankCove Digital Solutions",
  description: "Generated by RankCove",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        <Script
          src="https://kit.fontawesome.com/7379bf4ae1.js"
          crossOrigin="anonymous"
          strategy="afterInteractive" // Load this script after the page is interactive
        />
        <Script id="aos-init" strategy="afterInteractive">
          {`
            AOS.init();
          `}
        </Script>
      </head>
      <body className={inter.className}>
        <Header />
        {children}
        <Footer />
      </body>
    </html>
  );
}
